//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parcial3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Parcial3DBEntities1 : DbContext
    {
        public Parcial3DBEntities1()
            : base("name=Parcial3DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EstadoSolicitud> EstadoSolicitud { get; set; }
        public DbSet<Solicitante> Solicitante { get; set; }
        public DbSet<SolicitudPasaporte> SolicitudPasaporte { get; set; }
    }
}
