//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parcial3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitante
    {
        public Solicitante()
        {
            this.SolicitudPasaporte = new HashSet<SolicitudPasaporte>();
        }
    
        public int SolicitanteId { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Nacionalidad { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
    
        public virtual ICollection<SolicitudPasaporte> SolicitudPasaporte { get; set; }
    }
}
