//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace parcial3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPasaporte
    {
        public int SolicitudId { get; set; }
        public Nullable<int> SolicitanteId { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string TipoSolicitud { get; set; }
        public Nullable<int> EstadoSolicitudId { get; set; }
        public string Observaciones { get; set; }
    
        public virtual EstadoSolicitud EstadoSolicitud { get; set; }
        public virtual Solicitante Solicitante { get; set; }
    }
}
